### ISSUE TITLE
Suggested Resources for Paid Tutorials / Courses

### ISSUE THREAD

**Issue by tinjure20** [henrikwirth/awesome-wordpress-gatsby#13]
I have watched the following two courses by Morten Rand-Henriksen in LinkedIn Learning and found very useful. Thought you might like have look:

1. [Learning Gatsby](https://www.linkedin.com/learning/learning-gatsby?trk=learning-serp_learning_search-card&upsellOrderOrigin=public_profile_learning-search-bar_search-submit) - This step-by-step learning course helps to create Gatsby WordPress site using GraphQL.
2. [Building a Headless WordPress Site with Gatsby ](https://www.linkedin.com/learning/building-a-headless-wordpress-site-with-gatsby?trk=learning-serp_learning_search-card&upsellOrderOrigin=public_profile_learning-search-bar_search-submit)- This course is a step-by-step walk through using gatsby-source-wordpress plugin to create a fully functional headless Gatsby WordPress site with posts, pages, categories, tags, post navigation and other features.

**Comment by henrikwirth** [comment]
@tinjure20 Great resources. I would add the second since it is more related to WordPress with Gatsby. The first one seems more of a general Gatsby starting course.

Cheers for the suggestions
